name = "status-worker"
workers_dev = false
account_id = "0cee8561e3989abcad569632b8652767"
compatibility_date = "2022-10-06"
main = "src/index.ts"

[triggers]
crons = ["* * * * *"]

[[kv_namespaces]]
binding = "KV"
id = "2f55536c6656465c9a658be5491804f8"

[[previews.kv_namespaces]]
binding = "KV"
id = "2f55536c6656465c9a658be5491804f8"
